# Generated by Django 4.2.26 on 2026-01-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_number']},
        ),
        migrations.AddField(
            model_name='campus',
            name='school',
            field=models.ForeignKey(help_text='School this campus belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(help_text='School this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_campus_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'student_number'), name='unique_student_number_per_school'),
        ),
    ]
