# Generated by Django 4.2.26 on 2026-01-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0002_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='school',
            field=models.ForeignKey(help_text='School this reconciliation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.school'),
        ),
        migrations.AddField(
            model_name='statement',
            name='school',
            field=models.ForeignKey(help_text='School this statement belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='core.school'),
        ),
    ]
