# Generated by Django 4.2.26 on 2026-01-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(help_text='School this notification belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.school'),
        ),
    ]
