# Generated by Django 4.2.26 on 2025-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_term_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10),
        ),
    ]
