# Generated by Django 4.2.26 on 2025-11-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_bank_transfer_fields'),
        ('payments', '0006_profile_default_roles'),
    ]

    operations = [
    ]
