# Generated by Django 4.2.26 on 2026-01-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_reference_details'),
        ('payments', '0006_profile_default_roles'),
    ]

    operations = [
    ]
