# Generated by Django 4.2.26 on 2026-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merge_20260101_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_details',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='bank_name',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Boarding', 'Boarding'), ('Registration', 'Registration'), ('Other', 'Other')], default='Tuition', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='reference_id',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='''
                    DO $$
                    BEGIN
                        IF EXISTS(SELECT 1 FROM information_schema.columns 
                                  WHERE table_name='payments_payment' AND column_name='reference_number') THEN
                            ALTER TABLE payments_payment RENAME COLUMN reference_number TO reference_id;
                        ELSIF NOT EXISTS(SELECT 1 FROM information_schema.columns 
                                        WHERE table_name='payments_payment' AND column_name='reference_id') THEN
                            ALTER TABLE payments_payment ADD COLUMN reference_id VARCHAR(100);
                        END IF;
                    END $$;
                    ''',
                    reverse_sql='''
                    DO $$
                    BEGIN
                        IF EXISTS(SELECT 1 FROM information_schema.columns 
                                  WHERE table_name='payments_payment' AND column_name='reference_id') THEN
                            ALTER TABLE payments_payment RENAME COLUMN reference_id TO reference_number;
                        END IF;
                    END $$;
                    '''
                ),
            ],
        ),
    ]
