# Generated by Django 4.2.26 on 2026-01-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_reference_details_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding this payment', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When this payment was voided', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.CharField(blank=True, help_text='User who voided this payment', max_length=100, null=True),
        ),
    ]
