# Generated by Django 4.2.26 on 2026-01-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0009_add_void_tracking_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_receipt_per_term_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(help_text='School this payment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.school'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(help_text='School this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.school'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'academic_year', 'receipt_number'), name='unique_receipt_per_school_term_year'),
        ),
    ]
