# Generated by Django 4.2.26 on 2026-01-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_payment_unique_receipt_per_term_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
    ]
