# Generated by Django 4.2.26 on 2026-01-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School name', max_length=255)),
                ('code', models.CharField(help_text='Unique school code (e.g., SHINING001)', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='School contact email', max_length=254)),
                ('phone', models.CharField(help_text='School contact phone', max_length=20)),
                ('address', models.TextField(help_text='Physical address')),
                ('city', models.CharField(default='Harare', max_length=100)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text="Whether the school's subscription is active")),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter (< 150 students)'), ('growth', 'Growth (150-400 students)'), ('professional', 'Professional (400-800 students)'), ('enterprise', 'Enterprise (800+ students)')], default='starter', help_text='Pricing tier based on school size', max_length=50)),
                ('subscription_start_date', models.DateField(auto_now_add=True, help_text='Date school started subscription')),
                ('subscription_end_date', models.DateField(blank=True, help_text='Subscription expiry date (null = active)', null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=60.0, help_text='Monthly subscription fee in USD', max_digits=10)),
                ('whatsapp_phone_number', models.CharField(blank=True, help_text='WhatsApp bot number for this school', max_length=20, null=True, unique=True)),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Whether WhatsApp bot is enabled for this school')),
                ('logo_url', models.URLField(blank=True, help_text='URL to school logo', null=True)),
                ('primary_color', models.CharField(default='#1976d2', help_text='Primary brand color (hex format)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
